import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * pwa-ui-language AC9 — a regression tripwire, not a proof (tech-plan.md D13).
 *
 * AC9 explicitly accepts a heuristic. The value is catching the next
 * contributor who types a Spanish label straight into JSX six months from
 * now, at which point the `en` and `be` builds silently grow a Spanish hole.
 *
 * Comments are stripped before scanning. This codebase's comments are dense,
 * bilingual and deliberately so — scanning them would produce nothing but
 * noise and the test would be disabled within a week.
 */

const SRC_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const EXCLUDED = [
  'i18n/',                 // the catalogs are where Spanish belongs
  'data/guideContent.js',  // generated by scripts/build-guide-content.js, already per-locale
  'test-setup.js',
];

/**
 * Literals that are legitimately Spanish and are NOT UI chrome. Every entry
 * needs a reason. An empty list is the goal; a growing list is a smell.
 *
 * All four entries below are the SAME shape: a technical identifier (a
 * localStorage key or a static filename/path) that happens to contain the
 * bare word "rutina" — the app's own domain-noun namespace prefix, used the
 * same way `rutina:onboardingSeen` already was before this feature
 * (lib/onboardingStorage.js). None of these strings are ever rendered to a
 * user; the heuristic's word list has no way to distinguish "rutina" the
 * Spanish noun from "rutina" the identifier segment, so it is exactly the
 * kind of false positive AC9 accepts a heuristic for.
 */
const ALLOWLIST = [
  {
    file: 'lib/uiLangStorage.js',
    text: 'rutina:uiLang',
    why: 'localStorage key, not user-visible copy — same rutina: namespace convention as the pre-existing rutina:onboardingSeen key.',
  },
  {
    file: 'lib/onboardingStorage.js',
    text: 'rutina:onboardingSeen',
    why: 'localStorage key, not user-visible copy — pre-existing key, predates this feature.',
  },
  {
    file: 'lib/clubStorage.js',
    text: 'rutina:club',
    why: 'localStorage key, not user-visible copy — same rutina: namespace convention as rutina:uiLang / rutina:onboardingSeen (gym-directory-and-catalog D3).',
  },
  {
    file: 'lib/guideLocale.js',
    text: 'rutina-data-files.zip',
    why: 'static archive filename (GUIDE_DATA_ARCHIVE.filename), not user-visible prose.',
  },
  {
    file: 'lib/guideLocale.js',
    text: 'data/rutina-data-files.zip',
    why: 'static archive path (GUIDE_DATA_ARCHIVE.path), not user-visible prose.',
  },
];

function stripComments(source) {
  return source
    .replace(/\/\*[\s\S]*?\*\//g, ' ')
    .replace(/(^|[^:])\/\/[^\n]*/g, '$1 ');
}

const ACCENTED = /[áéíóúñüÁÉÍÓÚÑÜ¿¡]/;
const SPANISH_WORDS =
  /\b(de|la|el|los|las|del|para|con|una|sin|que|tus|hay|esta|este|todas|todos|desde|hasta|sesion|sesión|dia|día|dias|días|rutina|ejercicio|ejercicios|guardar|cerrar|volver|ver|programa|historial|progreso|catalogo|catálogo|inicio|ajustes|idioma|serie|series|repeticiones|peso|entrenamiento|semana|fase|equipo|maquina|máquina|nombre|fecha|hoy|ayer|ninguna|ninguno|cancelar|eliminar|borrar|importar|exportar|copiar|copiado|empezar|siguiente|atras|atrás|saltar|descargar|buscar|resultados|completada|completado|pendiente|activa|abandonada|registradas|todavia|todavía)\b/i;

function looksLikeSpanishCopy(text) {
  const value = text.trim();
  if (value.length < 3) return false;
  if (/^[\s\d\W]*$/.test(value)) return false;
  if (/^(https?:|\/|\.\/|\.\.\/|#|data:|var\(|calc\(|rgba?\()/.test(value)) return false;
  if (/^[a-z][a-zA-Z0-9-]*$/.test(value)) return false; // identifiers, css props, ids
  return ACCENTED.test(value) || SPANISH_WORDS.test(value);
}

function sourceFiles() {
  const out = [];
  (function walk(dir) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (/\.(js|jsx)$/.test(entry.name) && !/\.test\./.test(entry.name)) out.push(full);
    }
  })(SRC_DIR);
  return out.filter((f) => {
    const rel = path.relative(SRC_DIR, f).replace(/\\/g, '/');
    return !EXCLUDED.some((prefix) => rel.startsWith(prefix) || rel === prefix);
  });
}

function findings() {
  const hits = [];
  for (const file of sourceFiles()) {
    const rel = path.relative(SRC_DIR, file).replace(/\\/g, '/');
    const source = stripComments(fs.readFileSync(file, 'utf8'));

    const quoted = source.match(/'[^'\\\n]{3,}'|"[^"\\\n]{3,}"|`[^`\\$]{3,}`/g) || [];
    for (const literal of quoted) {
      const text = literal.slice(1, -1);
      if (looksLikeSpanishCopy(text)) hits.push({ file: rel, text });
    }

    const jsxText = source.match(/>[^<>{}\n]{3,}</g) || [];
    for (const node of jsxText) {
      const text = node.slice(1, -1);
      if (looksLikeSpanishCopy(text)) hits.push({ file: rel, text });
    }
  }
  return hits.filter(
    (hit) => !ALLOWLIST.some((allowed) => allowed.file === hit.file && allowed.text === hit.text)
  );
}

describe('no stray Spanish literals outside the catalogs (AC9)', () => {
  it('finds none in app/src', () => {
    const stray = findings();
    // The message is the point: a failure has to name the file and the string,
    // or nobody will act on it.
    expect(stray.map((h) => `${h.file}: ${h.text.trim().replace(/\s+/g, ' ').slice(0, 60)}`)).toEqual([]);
  });

  it('keeps the allowlist justified rather than used as a silencer', () => {
    for (const entry of ALLOWLIST) {
      expect(entry.file, 'allowlist entry needs a file').toBeTruthy();
      expect(entry.text, 'allowlist entry needs the literal').toBeTruthy();
      expect(entry.why, `allowlist entry for ${entry.file} needs a reason`).toBeTruthy();
    }
    expect(ALLOWLIST.length, 'allowlist should stay small — every entry is a hole in AC9').toBeLessThanOrEqual(8);
  });

  it('actually detects a stray literal when one exists (the tripwire has a trigger)', () => {
    // Guards against the failure mode where the heuristic quietly matches
    // nothing and the test passes forever.
    expect(looksLikeSpanishCopy('Sin sesiones registradas todavía.')).toBe(true);
    expect(looksLikeSpanishCopy('Elige un día de la semana')).toBe(true);
    expect(looksLikeSpanishCopy('flex-start')).toBe(false);
    expect(looksLikeSpanishCopy('var(--bf-ink)')).toBe(false);
  });
});
